### ISSUE TITLE
新增页面如何把label改成中文的？

### ISSUE THREAD

**Issue by herbieliang** [xiaoxuan6/login#1]
管理员添加和编辑页面如何把字段label设置成中文的，现在显示的‘Enabled’不是很友好

**Comment by xiaoxuan6** [comment]
代码跟新了，update一下，先添加如下代码

中文：修改resources/lang/zh-CN 添加

    'enabled'                => '状态',
    
英文：修改resources/lang/en 添加
    
    'enabled'                => 'status',

**Comment by herbieliang** [comment]
> 代码跟新了，update一下，先添加如下代码
> 
> 中文：修改resources/lang/zh-CN 添加
> 
> ```
> 'enabled'                => '状态',
> ```
> 英文：修改resources/lang/en 添加
> 
> ```
> 'enabled'                => 'status',
> ```

已更新，修正一个文档上的错误，这个语言设置应该是在admin.php语言文件里的，不是在validation.php语言文件里的，文档说明里写的不清楚
